# Generated by Django 3.1.4 on 2021-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='부서명'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='직위명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='duty',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=256, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='전화번호'),
        ),
    ]
