# Generated by Django 3.1.4 on 2021-03-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210223_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '부서'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '직위'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원'},
        ),
    ]
