# Generated by Django 3.1.4 on 2021-03-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210303_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-status', 'level', 'name'], 'verbose_name': '부서'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-status', 'level', 'name'], 'verbose_name': '직위'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-status', 'pk'], 'verbose_name': '회원'},
        ),
    ]
