# Generated by Django 3.1.4 on 2021-02-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('status', models.BooleanField(default=True, verbose_name='활성')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='본문')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='this_workspace_author', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='책임자')),
            ],
            options={
                'verbose_name': '워크스페이스',
                'ordering': ['-status', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('status', models.BooleanField(default=True, verbose_name='활성')),
                ('name', models.CharField(max_length=128, verbose_name='카테고리')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='this_schedulecategory_author', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '일정구분',
                'ordering': ['-status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('status', models.BooleanField(default=True, verbose_name='활성')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='본문')),
                ('started', models.DateTimeField(verbose_name='시작일시')),
                ('ended', models.DateTimeField(verbose_name='종료일시')),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='this_schedule_author', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedulecategory', verbose_name='일정구분')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.workspace', verbose_name='워크스페이스')),
            ],
            options={
                'verbose_name': '일정',
                'ordering': ['-status', 'pk'],
            },
        ),
    ]
