# Generated by Django 3.1.4 on 2021-03-02 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='workspace_attendees', to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='attendees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='참석자'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_leader', to=settings.AUTH_USER_MODEL, verbose_name='책임자'),
        ),
    ]
