# Generated by Django 3.1.4 on 2021-03-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20210302_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '일정'},
        ),
        migrations.AlterModelOptions(
            name='schedulecategory',
            options={'verbose_name': '일정구분'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': '업무'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.workspace', verbose_name='업무'),
        ),
    ]
