# Generated by Django 3.1.4 on 2021-03-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20210303_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-status', 'pk'], 'verbose_name': '일정'},
        ),
        migrations.AlterModelOptions(
            name='schedulecategory',
            options={'ordering': ['-status', 'name'], 'verbose_name': '일정구분'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-status', 'title'], 'verbose_name': '업무'},
        ),
    ]
